Sync options between multiple multiselects
optimistdigital/nova-multiselect-field pull request #100
Opened 2021-05-05 07:55 UTC by KasparRosin

Syncs options between multiple multiselects, disabled options that have already been used by another multiselect in the same sync group.

2021-05-05 08:09 UTC, Tarpsvo requested changes

2021-05-05 08:09 UTC, Tarpsvo commented on resources/js/components/FormField.vue
> +        console.log('VALUES', values);
console.log

2021-05-05 08:09 UTC, Tarpsvo commented on resources/js/components/FormField.vue
> +      console.log('syncOptions');
console.log

2021-05-05 08:09 UTC, Tarpsvo commented on src/Multiselect.php
> +        if (empty($syncGroup)) throw new Exception('Multiselect sync requires syncGroup, none provided.');
Mmm, ma vist teeks nii et if (empty($syncGroup)) $syncGroup = $this->attribute;

Teoorias peaks ühe lehe piires ->sync() 99% usecase ära täitma, sest vaevalt kasutajal on sama resource piires mitu sama attributega multiselect

2021-05-05 08:09 UTC, Tarpsvo commented on src/Multiselect.php
> +        return $this->withMeta(['sync' => "$syncGroup"]);
miks siin mingi explicit casting on :D piisab ilma "" variant ma arvan, sest PHP nkn valideerib kas $syncGroup on string v mitte

2021-05-05 08:09 UTC, Tarpsvo commented on src/Multiselect.php
> +    public function sync(string $syncGroup)
ma isiklikult oleks valinud mingi teise nimetuse sellele, sest ->sync() ja ->async() conflictivad praegu ja teevad täiesti teistsugust asja. Parem oleks näiteks ->distinct() või ->unique(), ma vist hääletaks distinct()

2021-05-05 08:09 UTC, Tarpsvo commented on resources/js/components/FormField.vue
> +          if (this.isMultiselect) syncValues.push(...values.map(value => value.label));
Ma ei mõista miks siin labeleid kasutatakse :D pigem peaks comparima groupi ja valuet, ei v?

2021-05-05 08:43 UTC, KasparRosin commented on resources/js/components/FormField.vue
> +          if (this.isMultiselect) syncValues.push(...values.map(value => value.label));
Siin võibolla peaks tõesti valuet võrdlema. Ma ei teadnud kas on väga vahet. 
Gruppi ei ole vaja võrrelda, kuna me saame eeldada, et ainult sama gruppi multiselectid kutsuvad selle callbacki.

2021-05-05 09:50 UTC, KasparRosin commented on resources/js/components/FormField.vue
> +          if (this.isMultiselect) syncValues.push(...values.map(value => value.label));
Lisasin suppordi option gruppidele.

2021-05-05 09:51 UTC, KasparRosin commented on src/Multiselect.php
> +    public function sync(string $syncGroup)
Distinct tundub norm ja.

2021-05-06 14:18 UTC, Tarpsvo approved these changes

2021-05-06 14:18 UTC, merged